# Generated by Django 3.1.5 on 2021-02-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('card_num', models.CharField(max_length=16)),
                ('card_exp', models.CharField(max_length=5)),
                ('card_code', models.CharField(max_length=3)),
            ],
        ),
    ]
