# Generated by Django 3.1.5 on 2021-03-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210329_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Fiction', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=4),
        ),
    ]
