# Generated by Django 3.1.5 on 2021-04-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20210330_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
