# Generated by Django 3.1.5 on 2021-04-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20210412_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
