# Generated by Django 3.1.5 on 2021-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20210414_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_exp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_num',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
