# Generated by Django 3.1.5 on 2021-04-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book')),
                ('cartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.cart')),
            ],
        ),
    ]
