# Generated by Django 3.1.5 on 2021-04-19 18:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_auto_20210419_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
