# Generated by Django 3.1.5 on 2021-04-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_auto_20210419_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
