# Generated by Django 3.1.5 on 2021-04-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
