# Generated by Django 3.1.5 on 2021-04-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_remove_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
