# Generated by Django 3.1.5 on 2021-04-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0021_ordermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderManager',
        ),
    ]
