# Generated by Django 3.1.5 on 2021-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0023_auto_20210420_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(default=27007924, primary_key=True, serialize=False),
        ),
    ]
