# Generated by Django 3.1.5 on 2021-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0024_auto_20210420_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='6904648622', max_length=10, primary_key=True, serialize=False),
        ),
    ]
