# Generated by Django 3.1.5 on 2021-04-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0031_auto_20210420_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Confirmed', max_length=255),
        ),
    ]
